name: Deploy to Github pages

on:
  push:
    branches: [ 'main' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Install trunk
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: trunk

      - name: Run tests
        run: cargo test --verbose

      - name: Build
        run: trunk build --release --public-url=qubit

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist